version: 2
jobs:
  test:
    working_directory: ~/home/circleci/chardonnay
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/node:18.17.1-stretch-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run vitest

  publish-npm:
    working_directory: ~/home/circleci/chardonnay
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/node:18.17.1-stretch-browsers
    steps:
      - checkout
      - run: npm install
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run: npm publish

  deploy-prod:
    docker:
      - image: circleci/node:18.17.1
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install
      - run: npm build
      - run: AWS_ACCESS_KEY_ID=$aws_access_key_production AWS_SECRET_ACCESS_KEY=$aws_secret_access_key_production
      - run: aws configure set default.region us-east-1
      - run: aws configure set aws_access_key_id $aws_access_key_production
      - run: aws configure set aws_secret_access_key $aws_secret_access_key_production
      - run: aws s3 cp build/static/js/main.js s3://evino-static-production/assets/twilio-conversations.js --acl public-read
      - run: aws s3 cp website/index.js s3://evino-static-production/assets/twilio-conversations-main.js --acl public-read

workflows:
  version: 2
  build-and-publish:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - publish-npm:
          requires:
            - test
          filters:
            tags:
              only: /^release-V_.*/
            branches:
              only: main
      - deploy-prod:
          filters:
            tags:
              only: /^release-V_.*/
            branches:
              ignore: /.*/
