version: 2
jobs:
  test-job:
    working_directory: ~/home/circleci/chardonnay
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/node:18.17.1-stretch-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test -- --runInBand --coverage --bail

  publish-npm-job:
    working_directory: ~/<WORKING DIR>/build
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/node:18.17.1-stretch-browsers
    steps:
      - checkout
      - run: npm install
      - run:
          command: |
            git config user.email "<YOUR EMAIL>"
            git config user.name "<YOUR NAME>"
      - run: npm version --minor
      - run: npm publish
      - run: git commit --amend -m "$(git log -1 --pretty=%B) [ci skip]"
      - run: git push origin $CIRCLE_BRANCH --tags

workflows:
  version: 2
  build-and-publish:
    jobs:
      - test-job:
          filters:
            branches:
              only: master
      - publish-npm-job:
          requires:
            - test-job
          filters:
            branches:
              only: master
