version: 2

defaults: &defaults
  working_directory: ~/home/circleci/chardonnay

jobs:
  build:
    <<: *defaults
    docker:
      - image: cimg/node:18.17.1
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run test

  test:
    <<: *defaults
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run test

  publish-npm:
    <<: *defaults
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - run: npm install
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run: npm publish

  deploy-prod:
    docker:
      - image: cimg/node:18.17.1
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: cd /home/circleci/chardonnay
      - run: npm install
      - run: npm run build
      - run: AWS_ACCESS_KEY_ID=$aws_access_key_production AWS_SECRET_ACCESS_KEY=$aws_secret_access_key_production
      - run: aws configure set default.region us-east-1
      - run: aws configure set aws_access_key_id $aws_access_key_production
      - run: aws configure set aws_secret_access_key $aws_secret_access_key_production
      - run: aws s3 cp storybook-static s3://evino-static-production/storybook-static/index.html --recursive --acl public-read

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^release-V_.*/
      - test:
          filters:
            branches:
              only: main
      - publish-npm:
          requires:
            - test
          filters:
            tags:
              only: /^release-V_.*/
            branches:
              only: main
      - deploy-prod:
          filters:
            tags:
              only: /^release-V_.*/
            branches:
              only: main
