export { PaymentMethodsContainer as Root } from './PaymentMethodsContainer'
export { ContentStyled as Content } from './PaymentMethodsComplement'
export { PaymentMethodsTitle as Title } from './PaymentMethodsTitle'
export { InstallmentStyle as Items } from './PaymentMethodsInstallment'
export { PaymentMethodsSubItems as SubItems } from './PaymentMethodsSubItems'
