name: Publish Package to npmjs

on:
  workflow_dispatch:
  push:
    tags:
      - 'release-V_*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish-npm:
    needs: test
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: git config --global user.name "${GITHUB_ACTOR}"
      - run: git config --global user.email "${GITHUB_ACTOR_EMAIL}"

      - name: View the information of the pusher
        run: |
          echo "The name of the pusher: ${{ github.event.pusher.name }}"
          echo "The email of the pusher: ${{ github.event.pusher.email }}"
          echo "The name GITHUB_ACTOR: ${{ GITHUB_ACTOR}}"
          echo "The email of the pusher: ${{ GITHUB_ACTOR_EMAIL }}"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
      - run: npm ci

      - name: Increment Package Version
        run: npm version patch -m "[RELEASE] %s"
      - run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
