name: Publish Page

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish-page:
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Publish Page
        run: npm ci
      - run: npm run deploy-storybook