name: Publish Package to npmjs

on:
  workflow_dispatch:
  push:
    tags:
      - 'release-V_*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish-npm:
    needs: test

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/release-V_')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
      - run: npm ci

      - name: Increment Package Version
        run: npx version -m "Bump version to %s [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
